apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingest-relay.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ingest-relay.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
